# Generated by Django 6.1.1 on 2026-09-30 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('display_name', models.CharField(max_length=20)),
                ('bio_text', models.TextField(blank=True)),
                ('joined', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
