# Generated by Django 6.1.1 on 2026-10-07 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_insta', '0003_post_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='timeStamp',
            new_name='timestamp',
        ),
        migrations.AddField(
            model_name='photo',
            name='image_file',
            field=models.ImageField(blank=True, upload_to='mini_insta/'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
